services: 
  tutorai-mongo: 
    image: mongo:latest
    container_name: tutorai-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mingo_init.sh:/docker-entrypoint-initdb.d/mongo_init.sh
    env_file:
      - $HOME/REPO/secrets/tutorai.env
    networks:
      - tutorai-network

  tutorai-chat-engine:
    build:
      context: ../chat_engine
      dockerfile: Dockerfile
    container_name: tutorai-chat-engine
    volumes:
      - ../chat_engine/data:/app/data
      - ../chat_engine/config.json:/app/config.json
    ports:
      - "65501:65501"
    networks:
      - tutorai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  mongo_data:

networks:
  tutorai-network:
