services: 
  tutorai-mongo: 
    image: mongo:latest
    container_name: tutorai-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mingo_init.sh:/docker-entrypoint-initdb.d/mongo_init.sh
    env_file:
      - /home/vincent/REPO/secrets/tutor.env
    networks:
      - tutorai-network

volumes:
  mongo_data:

networks:
  tutorai-network:
